
#Lets first make a error
# x = {1,2,3}
# y = 2
# z = 3
#
# result = y + z
#result2 = x + y
#print(result2)#unsupported operand type(s) for +: 'set' and 'int' as we are concatenate two different type


#we are importing python debugger
#pdb means debugger

# import pdb
#
#
# x = [1,3,4]
# y = 2
# z = 3
#
# result = y + z
# print(result)
#
# # Set a trace using Python Debugger, we do it before error line
# pdb.set_trace()
#
# result2 = y+x # this the line will give error
# print(result2)
#
# # go to this website about python debugging
# https://docs.python.org/3/library/pdb.html


